[profile.default]
solc = "0.8.15"
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read", path = "./artifacts/"}]
optimizer_runs = 1000000

# fuzz settings
[profile.default.fuzz]
runs = 256
[profile.intense.fuzz]
runs = 10_000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
single_line_statement_blocks = "single"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config